[2022-08-01 15:59:47,905] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: weather_dag.weather manual__2022-08-01T15:59:42.038455+00:00 [queued]>
[2022-08-01 15:59:47,928] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: weather_dag.weather manual__2022-08-01T15:59:42.038455+00:00 [queued]>
[2022-08-01 15:59:47,930] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-01 15:59:47,931] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-08-01 15:59:47,933] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-01 15:59:47,965] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): weather> on 2022-08-01 15:59:42.038455+00:00
[2022-08-01 15:59:47,978] {standard_task_runner.py:52} INFO - Started process 205 to run task
[2022-08-01 15:59:47,992] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'weather', 'manual__2022-08-01T15:59:42.038455+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmps8aslrkf', '--error-file', '/tmp/tmp3pl330vd']
[2022-08-01 15:59:47,998] {standard_task_runner.py:80} INFO - Job 59: Subtask weather
[2022-08-01 15:59:48,183] {task_command.py:371} INFO - Running <TaskInstance: weather_dag.weather manual__2022-08-01T15:59:42.038455+00:00 [running]> on host ced0d753a54e
[2022-08-01 15:59:48,375] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weather_dag
AIRFLOW_CTX_TASK_ID=weather
AIRFLOW_CTX_EXECUTION_DATE=2022-08-01T15:59:42.038455+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-01T15:59:42.038455+00:00
[2022-08-01 15:59:48,383] {logging_mixin.py:115} INFO - ETL Pipeline
[2022-08-01 15:59:48,385] {logging_mixin.py:115} INFO - Extraction stage started...
[2022-08-01 15:59:48,942] {logging_mixin.py:115} INFO - Transform stage started...
[2022-08-01 15:59:48,970] {logging_mixin.py:115} INFO - Data is valid, proceed to load stage.
[2022-08-01 15:59:48,973] {logging_mixin.py:115} INFO - Load stage started...
[2022-08-01 15:59:49,019] {logging_mixin.py:115} INFO -              Daytime         Day   Hour  Temperature  is Day  Humidity
0   2022-07-28 00:00  2022-07-28  00:00         74.8       0        88
1   2022-07-28 01:00  2022-07-28  01:00         74.7       0        88
2   2022-07-28 02:00  2022-07-28  02:00         74.5       0        88
3   2022-07-28 03:00  2022-07-28  03:00         74.3       0        89
4   2022-07-28 04:00  2022-07-28  04:00         74.3       0        88
5   2022-07-28 05:00  2022-07-28  05:00         74.3       0        88
6   2022-07-28 06:00  2022-07-28  06:00         74.3       0        88
7   2022-07-28 07:00  2022-07-28  07:00         76.5       1        80
8   2022-07-28 08:00  2022-07-28  08:00         78.7       1        73
9   2022-07-28 09:00  2022-07-28  09:00         81.0       1        65
10  2022-07-28 10:00  2022-07-28  10:00         84.0       1        63
11  2022-07-28 11:00  2022-07-28  11:00         87.1       1        60
12  2022-07-28 12:00  2022-07-28  12:00         90.1       1        58
13  2022-07-28 13:00  2022-07-28  13:00         88.6       1        59
14  2022-07-28 14:00  2022-07-28  14:00         87.1       1        60
15  2022-07-28 15:00  2022-07-28  15:00         85.6       1        61
16  2022-07-28 16:00  2022-07-28  16:00         84.5       1        64
17  2022-07-28 17:00  2022-07-28  17:00         83.4       1        66
18  2022-07-28 18:00  2022-07-28  18:00         82.2       1        69
19  2022-07-28 19:00  2022-07-28  19:00         80.6       1        74
20  2022-07-28 20:00  2022-07-28  20:00         79.0       0        78
21  2022-07-28 21:00  2022-07-28  21:00         77.4       0        83
22  2022-07-28 22:00  2022-07-28  22:00         76.6       0        84
23  2022-07-28 23:00  2022-07-28  23:00         75.9       0        84
[2022-08-01 15:59:49,021] {logging_mixin.py:115} INFO - Database open successfully
[2022-08-01 15:59:49,049] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1782, in _execute_context
    self.dialect.do_executemany(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 716, in do_executemany
    cursor.executemany(statement, parameters)
sqlite3.OperationalError: table weather has no column named Hour

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/script/WeatherETL.py", line 174, in run_weather_etl
    weather_df.to_sql("weather", engine, index=False, if_exists='append')
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 2951, in to_sql
    return sql.to_sql(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 697, in to_sql
    return pandas_sql.to_sql(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1739, in to_sql
    total_inserted = sql_engine.insert_records(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1332, in insert_records
    raise err
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1322, in insert_records
    return table.insert(chunksize=chunksize, method=method)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 950, in insert
    num_inserted = exec_insert(conn, keys, chunk_iter)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 857, in _execute_insert
    result = conn.execute(self.table.insert(), data)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1289, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1481, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1845, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2026, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1782, in _execute_context
    self.dialect.do_executemany(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 716, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) table weather has no column named Hour
[SQL: INSERT INTO weather ("Daytime", "Day", "Hour", "Temperature", "is Day", "Humidity") VALUES (?, ?, ?, ?, ?, ?)]
[parameters: (('2022-07-28 00:00', '2022-07-28', '00:00', 74.8, 0, 88), ('2022-07-28 01:00', '2022-07-28', '01:00', 74.7, 0, 88), ('2022-07-28 02:00', '2022-07-28', '02:00', 74.5, 0, 88), ('2022-07-28 03:00', '2022-07-28', '03:00', 74.3, 0, 89), ('2022-07-28 04:00', '2022-07-28', '04:00', 74.3, 0, 88), ('2022-07-28 05:00', '2022-07-28', '05:00', 74.3, 0, 88), ('2022-07-28 06:00', '2022-07-28', '06:00', 74.3, 0, 88), ('2022-07-28 07:00', '2022-07-28', '07:00', 76.5, 1, 80)  ... displaying 10 of 24 total bound parameter sets ...  ('2022-07-28 22:00', '2022-07-28', '22:00', 76.6, 0, 84), ('2022-07-28 23:00', '2022-07-28', '23:00', 75.9, 0, 84))]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2022-08-01 15:59:49,115] {taskinstance.py:1415} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_dag, task_id=weather, execution_date=20220801T155942, start_date=20220801T155947, end_date=20220801T155949
[2022-08-01 15:59:49,166] {standard_task_runner.py:92} ERROR - Failed to execute job 59 for task weather ((sqlite3.OperationalError) table weather has no column named Hour
[SQL: INSERT INTO weather ("Daytime", "Day", "Hour", "Temperature", "is Day", "Humidity") VALUES (?, ?, ?, ?, ?, ?)]
[parameters: (('2022-07-28 00:00', '2022-07-28', '00:00', 74.8, 0, 88), ('2022-07-28 01:00', '2022-07-28', '01:00', 74.7, 0, 88), ('2022-07-28 02:00', '2022-07-28', '02:00', 74.5, 0, 88), ('2022-07-28 03:00', '2022-07-28', '03:00', 74.3, 0, 89), ('2022-07-28 04:00', '2022-07-28', '04:00', 74.3, 0, 88), ('2022-07-28 05:00', '2022-07-28', '05:00', 74.3, 0, 88), ('2022-07-28 06:00', '2022-07-28', '06:00', 74.3, 0, 88), ('2022-07-28 07:00', '2022-07-28', '07:00', 76.5, 1, 80)  ... displaying 10 of 24 total bound parameter sets ...  ('2022-07-28 22:00', '2022-07-28', '22:00', 76.6, 0, 84), ('2022-07-28 23:00', '2022-07-28', '23:00', 75.9, 0, 84))]
(Background on this error at: https://sqlalche.me/e/14/e3q8); 205)
[2022-08-01 15:59:49,214] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-01 15:59:49,310] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
