[2022-08-01 14:46:52,055] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: weather_dag.weather manual__2022-08-01T14:46:49.305285+00:00 [queued]>
[2022-08-01 14:46:52,080] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: weather_dag.weather manual__2022-08-01T14:46:49.305285+00:00 [queued]>
[2022-08-01 14:46:52,082] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-01 14:46:52,084] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-08-01 14:46:52,085] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-01 14:46:52,119] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): weather> on 2022-08-01 14:46:49.305285+00:00
[2022-08-01 14:46:52,136] {standard_task_runner.py:52} INFO - Started process 1236 to run task
[2022-08-01 14:46:52,149] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'weather', 'manual__2022-08-01T14:46:49.305285+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpsp6vx2p9', '--error-file', '/tmp/tmpinr8lif_']
[2022-08-01 14:46:52,155] {standard_task_runner.py:80} INFO - Job 35: Subtask weather
[2022-08-01 14:46:52,539] {task_command.py:371} INFO - Running <TaskInstance: weather_dag.weather manual__2022-08-01T14:46:49.305285+00:00 [running]> on host 43173a86041a
[2022-08-01 14:46:52,669] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weather_dag
AIRFLOW_CTX_TASK_ID=weather
AIRFLOW_CTX_EXECUTION_DATE=2022-08-01T14:46:49.305285+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-01T14:46:49.305285+00:00
[2022-08-01 14:46:52,673] {logging_mixin.py:115} INFO - ETL Pipeline
[2022-08-01 14:46:52,675] {logging_mixin.py:115} INFO - Extraction stage started...
[2022-08-01 14:46:53,017] {logging_mixin.py:115} INFO - Transform stage started...
[2022-08-01 14:46:53,033] {logging_mixin.py:115} INFO - Data is valid, proceed to load stage.
[2022-08-01 14:46:53,035] {logging_mixin.py:115} INFO - Load stage started...
[2022-08-01 14:46:53,039] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/script/WeatherETL.py", line 153, in run_weather_etl
    conn = sqlite3.connect('/weather_data.sqlite')
sqlite3.OperationalError: unable to open database file
[2022-08-01 14:46:53,071] {taskinstance.py:1415} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_dag, task_id=weather, execution_date=20220801T144649, start_date=20220801T144652, end_date=20220801T144653
[2022-08-01 14:46:53,109] {standard_task_runner.py:92} ERROR - Failed to execute job 35 for task weather (unable to open database file; 1236)
[2022-08-01 14:46:53,168] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-01 14:46:53,476] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
