[2022-08-01 16:10:46,375] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: weather_dag.weather manual__2022-08-01T16:10:40.565535+00:00 [queued]>
[2022-08-01 16:10:46,399] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: weather_dag.weather manual__2022-08-01T16:10:40.565535+00:00 [queued]>
[2022-08-01 16:10:46,400] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-01 16:10:46,402] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-08-01 16:10:46,404] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-01 16:10:46,434] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): weather> on 2022-08-01 16:10:40.565535+00:00
[2022-08-01 16:10:46,446] {standard_task_runner.py:52} INFO - Started process 44 to run task
[2022-08-01 16:10:46,456] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'weather', 'manual__2022-08-01T16:10:40.565535+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpkfmhxxff', '--error-file', '/tmp/tmpsz_blbmi']
[2022-08-01 16:10:46,459] {standard_task_runner.py:80} INFO - Job 67: Subtask weather
[2022-08-01 16:10:46,650] {task_command.py:371} INFO - Running <TaskInstance: weather_dag.weather manual__2022-08-01T16:10:40.565535+00:00 [running]> on host ced0d753a54e
[2022-08-01 16:10:46,838] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weather_dag
AIRFLOW_CTX_TASK_ID=weather
AIRFLOW_CTX_EXECUTION_DATE=2022-08-01T16:10:40.565535+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-01T16:10:40.565535+00:00
[2022-08-01 16:10:46,844] {logging_mixin.py:115} INFO - ETL Pipeline
[2022-08-01 16:10:46,846] {logging_mixin.py:115} INFO - Extraction stage started...
[2022-08-01 16:10:47,397] {logging_mixin.py:115} INFO - Transform stage started...
[2022-08-01 16:10:47,422] {logging_mixin.py:115} INFO - Data is valid, proceed to load stage.
[2022-08-01 16:10:47,426] {logging_mixin.py:115} INFO - Load stage started...
[2022-08-01 16:10:47,438] {logging_mixin.py:115} INFO - Database open successfully
[2022-08-01 16:10:47,441] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/script/WeatherETL.py", line 172, in run_weather_etl
    tdata.to_sql("weather", conn=engine.get_bind(), index=False, if_exists='append')
AttributeError: 'Engine' object has no attribute 'get_bind'
[2022-08-01 16:10:47,498] {taskinstance.py:1415} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_dag, task_id=weather, execution_date=20220801T161040, start_date=20220801T161046, end_date=20220801T161047
[2022-08-01 16:10:47,545] {standard_task_runner.py:92} ERROR - Failed to execute job 67 for task weather ('Engine' object has no attribute 'get_bind'; 44)
[2022-08-01 16:10:47,596] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-01 16:10:47,668] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
